### ISSUE TITLE
Rényi DP Accountant - Sampled Gaussian Mechanism - Reference?

### ISSUE THREAD

**Issue by MrinankSharma** [tensorflow/privacy#55] opened 2019-07-03 16:59 UTC
Hi all, 

I was wondering whether there was a reference for the Rényi DP accountant, more specifically, the code applied when sub-sampling is involved? I saw this issue: https://github.com/tensorflow/privacy/issues/13 

and was wondering whether the paper had been released yet. If not, would it be possible to share a draft?

Best,

**Comment by npapernot** [comment] 2019-07-16 05:27
Hi @MrinankSharma, unfortunately the paper has not been released yet, I'll close this issue since it is a duplicate of #13. Thanks for your patience!

**Closed by npapernot** 2019-07-16 05:27 UTC
