### ISSUE TITLE
No module named "tensorflow_privacy"

### ISSUE THREAD

**Issue by shilinni** [tensorflow/privacy#44] opened 2019-04-12 04:02 UTC
4 hours ago a change was made to privacy/privacy/__init__.py. I'm using Google Colab for a project and this change leads to a module error: 'No module named "tensorflow_privacy' ". Removing all the "tensorflow_privacy." corrects it.

**Comment by ilyamironov** [comment] 2019-04-12 16:56
Thanks for reporting it! Can you share the part of the script that is failing? What runtime do you use (hosted or local)?

**Comment by shilinni** [comment] 2019-04-12 17:09
> Thanks for reporting it! Can you share the part of the script that is failing? What runtime do you use (hosted or local)?

I used hosted runtime. I simply called "from privacy.analysis.rdp_accountant import compute_rdp". The error msg is like the following: 
"/content/privacy/privacy/__init__.py in <module>()
     21   pass
     22 else:
---> 23   from tensorflow_privacy.privacy.analysis.privacy_ledger import DummyLedger
     24   from tensorflow_privacy.privacy.analysis.privacy_ledger import GaussianSumQueryEntry
     25   from tensorflow_privacy.privacy.analysis.privacy_ledger import PrivacyLedger

ModuleNotFoundError: No module named 'tensorflow_privacy'
" 

So I changed the init.py to:

from privacy.analysis.privacy_ledger import DummyLedger
from privacy.analysis.privacy_ledger import GaussianSumQueryEntry	
from privacy.analysis.privacy_ledger import PrivacyLedger	
from privacy.analysis.privacy_ledger import QueryWithLedger	
from privacy.analysis.privacy_ledger import SampleEntry
from privacy.dp_query.dp_query import DPQuery	
from privacy.dp_query.gaussian_query import GaussianAverageQuery	
from privacy.dp_query.gaussian_query import GaussianSumQuery	
from privacy.dp_query.nested_query import NestedQuery	
from privacy.dp_query.no_privacy_query import NoPrivacyAverageQuery	
from privacy.dp_query.no_privacy_query import NoPrivacySumQuery	
from privacy.dp_query.normalized_query import NormalizedQuery
from privacy.optimizers.dp_optimizer import DPAdagradGaussianOptimizer
from privacy.optimizers.dp_optimizer import DPAdagradOptimizer
from privacy.optimizers.dp_optimizer import DPAdamGaussianOptimizer
from privacy.optimizers.dp_optimizer import DPAdamOptimizer 
from privacy.optimizers.dp_optimizer import DPGradientDescentGaussianOptimizer
from privacy.optimizers.dp_optimizer import DPGradientDescentOptimizer

**Comment by npapernot** [comment] 2019-04-12 17:37
Thanks, it looks like there was an issue when copying recent changes merged by @galenmandrew, the migration tool did not rewrite the imports properly. We can definitely fix that

**Comment by photofum** [comment] 2019-10-19 19:18
I am traying to run mnist_dpsgd_tutorial but it has error:
ModuleNotFoundError: No module named 'tensorflow_privacy'

**Comment by schien1729** [comment] 2019-10-21 03:18
Hi there,

I just tried it myself on a new cloud instance, and it works for me. Can you tell me what steps will reproduce this error for you?

One thing to note it that we did push out a new version, 0.2.0, last week, that reorganized the directory structure a little. If you try recloning and reinstalling, does it work?

Thanks!
Steve

**Comment by jfraj** [comment] 2019-10-23 19:06
Here is an example using the first tensoflow privacy line of the mnist_dpsgd_tutorial mentioned by @photofum :

- In Google Colab : create a new python 3 notebook
- In the first cell type : from tensorflow_privacy.privacy.analysis import privacy_ledger

result :
ModuleNotFoundError: No module named 'tensorflow_privacy'

Of course, the simple command "import tensorflow_privacy" leads to the same result

**Comment by schien1729** [comment] 2019-10-23 20:01
Okay, I'll look into it. In the meantime, if you do

pip install tensorflow_privacy

at the beginning of your colab, does that work as a workaround for now?

**Comment by jfraj** [comment] 2019-10-23 20:04
Yes @schien1729, I updated my comment to mention it

**Comment by schien1729** [comment] 2019-10-24 20:37
Thanks. Do you happen to know the most recent time `import tensorflow_privacy` did work?

**Comment by jfraj** [comment] 2019-10-24 23:45
No, sorry. It never worked for me without `!pip install`, but I only started using it since a couple of days.

**Comment by schien1729** [comment] 2019-10-30 22:38
Okay, I've consulted with the appropriate Colab teams, and this is expected behavior, as shown in [our own Colab](https://github.com/tensorflow/privacy/blob/master/tutorials/Classification_Privacy.ipynb). This may change in the future, but that's the current situation.

Thanks!

**Closed by schien1729** 2019-10-30 22:38 UTC

**Comment by photofum** [comment] 2019-10-31 06:39
Hi,
Thanks for your reply. I will use it.
ala
