### ISSUE TITLE
mnist_dpsgd_tutorial_keras error

### ISSUE THREAD

**Issue by luoling1993** [tensorflow/privacy#27] opened 2019-03-11 02:19 UTC
When I run the mnist_dpsgd_tutorial_keras.py, get a error "ValueError: Dimension size must be evenly divisible by 250 but is 1 for 'training/TFOptimizer/Reshape' (op: 'Reshape') with input shapes: [], [2] and with input tensors computed as partial shapes: input[1] = [250,?]."

**Comment by luoling1993** [comment] 2019-03-11 02:20
python version: 3.7
tensorflow version: 1.13.1

**Comment by jvmancuso** [comment] 2019-03-11 03:46
This is a duplicate of #17 and #21. I'd recommend checking those out.

Accordingly, I think this issue can be closed.

**Closed** 2019-03-11 04:21 UTC

**Comment by cuizhiqiang888** [comment] 2020-07-01 00:41
I also met the same problem is how to solve
thanks

**Comment by sharmi1206** [comment] 2020-07-14 12:58
Raised. a similar issue at https://github.com/tensorflow/privacy/issues/113

Can somebody help?
